sudo: false
language: c

branches:
  only:
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/

addons:
  apt:
    packages:
    - luarocks

install: luarocks install --local luacheck

script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: always
    on_failure: always
